# Generated by Django 4.0.2 on 2022-07-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticefile',
            name='files',
        ),
        migrations.AddField(
            model_name='noticefile',
            name='document_link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='submittedlink',
            name='doc_link',
            field=models.URLField(default='', null=True),
        ),
    ]
