# Generated by Django 4.0.2 on 2022-06-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedlink',
            name='doc_link',
            field=models.URLField(default=None),
        ),
    ]
