# Generated by Django 4.0.2 on 2022-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_submittedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedlink',
            name='youtube_link',
            field=models.URLField(default=None),
        ),
    ]
