# Generated by Django 4.0.2 on 2022-06-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_notices_notice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='notice_name',
            field=models.CharField(max_length=100),
        ),
    ]
