# Generated by Django 4.0.2 on 2022-07-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_noticefile_files_noticefile_document_link_and_more'),
        ('courses', '0003_alter_submission_marks'),
    ]

    operations = [
    ]
