# Generated by Django 4.0.2 on 2022-07-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_notices_notice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticefile',
            name='files',
        ),
        migrations.AddField(
            model_name='noticefile',
            name='document_link',
            field=models.URLField(default=None),
        ),
    ]
