# Generated by Django 4.0.2 on 2022-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_submittedlink_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedlink',
            name='youtube_link',
            field=models.URLField(default=None),
        ),
    ]
